spring.application.name=producto-app

spring.datasource.url=jdbc:mysql://localhost:3306/producto_db
spring.datasource.username=root
spring.datasource.password=Susana

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
